version: '3.3'
services:
  nginx:
    image: nginx
    restart: always
    volumes:
      - ./data/marzban/run:/run
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - "./www:/www"


  marzban-node:
    image: gozargah/marzban-node:latest
    restart: always
    network_mode: host

    environment:
      SSL_CLIENT_CERT_FILE: "/var/lib/marzban/ssl_client_cert.pem"
      XRAY_EXECUTABLE_PATH: "/var/lib/marzban/xray-core/xray"
      - TZ=Asia/Tehran
      - DEBIAN_FRONTEND=noninteractive      

    volumes:
      - /var/lib/marzban-node:/var/lib/marzban-node
      - ./data:/var/lib/marzban
      - ./data/marzban/run:/run





